title: 天行者
tagline: 山本无忧,因雪白头
description: 梦想的道路上总是充满荆棘,如果畏惧的话,又如何到达传说的彼岸,去看那最美的风景
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://tianxingzhe.xyz # the base hostname & protocol for your site

author:
  name: TimeOfPassage
  email: 1376246506@qq.com
  github: TimeOfPassage
  twitter: 
  weibo: 
start_year: 2017

permalink: /:year/:month/:day/:title
timezone: Asia/Shanghai

tags_path: /tags.html
feed_path: /feed.xml

markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

service:
  comment: duoshuo
  disqus:
    short_name: evercoding
  duoshuo: 
    short_name: evercoding
  google:
    tracking_id : UA-54098391-1
  baidu:
    num: 286a0fd3582530031faa80f383f53a77

exclude: [README.md, CNAME]
  
